version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/kt_library
    overwrite: true

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 1200
      runas: ec2-user
