version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/kt_library
    overwrite: true

permissions:
  - object: /home/ec2-user/kt_library
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ec2-user
